#!/bin/bash

echo "Removing existing files" && \
ssh deployer@www.goodcity.hk 'rm -rf /var/www/html/www.goodcity.hk/*' && \
echo "Uploading new files" && \
scp -r * deployer@www.goodcity.hk:/var/www/html/www.goodcity.hk/ &&
echo "Removing existing files" && \
ssh deployer@www.goodcity.hk -p 62423 'rm -rf /var/www/html/www.goodcity.hk/*' && \
echo "Uploading new files" && \
scp -r -P 62423 * deployer@www.goodcity.hk:/var/www/html/www.goodcity.hk/
